### ISSUE TITLE
Commercials not marked after recording done.

### ISSUE THREAD

**Issue by tmikkonen** [essandess/etv-comskip#64]
OS X 10.11.1, EyeTV 3.6.8 (build 7407), tried with ETVComskip 3.3.1 & 3.3.2

El Capitan freshly installed from scratch, EyeTV Preferences restored from Mountain Lion with the EyeTV Reporter Utility from Elgato Systems.

First, I installed ETVComskip 3.3.1 but commercials were not marked with new recordings nor were they skipped if present in old recordings.
Then I noticed that for some reason ~/Library/LaunchAgents was not a directory but a file that had the contents of com.github.essandess.etv-comskip.comskipper.plist. I removed the file and re-created ~/Library/LaunchAgents directory and installed 3.3.2, which was now the latest version.

Again, commercials are not marked but this time they are skipped in old recordings. I then uninstalled and re-installed 3.3.2 (and logged out and tried also rebooting) but the situation has not changed.

If I run bin/comskip and bin/MarkCommercials manually on the mpg file inside new recordings, the commercials are marked correctly (and they are skipped like they're supposed to when watching the recordings).

So, my first guess was that RecordingDone.scpt isn't run for some reason when the recording stops. However, TriggeredScriptBridge does show up in Activity Monitor so I'm not so sure anymore.

My EyeTV Archive is in /Volumes/EyeTV\ HD/ on an external drive, but I don't think that should make any difference.

> $ ls -l /Library/Application\ Support/EyeTV/Scripts/TriggeredScripts/
> total 192
> -rw-r--r--@ 1 root  admin  60670 Nov 22 22:24 ExportDone.scpt
> -rw-r--r--@ 1 root  admin  26398 Nov 22 22:24 RecordingDone.scpt
> -rw-r--r--@ 1 root  admin   5930 Nov 22 22:24 RecordingStarted.scpt

> $ ls -al ~/Library/LaunchAgents/
> total 16
> drwxr-----   4 user  staff   136 Nov 22 22:24 .
> drwx------@ 50 user  staff  1700 Nov 19 00:03 ..
> -rw-r--r--@  1 user  staff   482 Nov 22 22:24 com.github.essandess.etv-comskip.comskipper.plist

> ls -l /Library/Application\ Support/ETVComskip/
> total 120
> -rw-r--r--@  1 macports  staff   1055 Nov 17 04:26 AUTHORS
> drwxr-xr-x@  3 macports  staff    102 Nov 17 04:26 Install ETVComskip.app
> -rw-r--r--@  1 macports  staff  17987 Nov 17 04:26 LICENSE
> -rw-r--r--@  1 macports  staff  18300 Nov 17 04:26 LICENSE.rtf
> drwxr-xr-x@  3 macports  staff    102 Nov 17 04:26 UnInstall ETVComskip.app
> drwxr-xr-x@ 16 macports  staff    544 Nov 17 04:26 bin
> -rw-r--r--@  1 macports  staff   6340 Nov 17 04:25 comskip.ini
> -rw-r--r--@  1 macports  staff   6340 Nov 17 04:25 comskip.ini.us_cabletv
> drwxr-xr-x@ 57 macports  staff   1938 Nov 17 04:26 lib
> drwxr-xr-x@  9 macports  staff    306 Nov 17 04:26 scripts

> $ ls -l /Volumes/EyeTV\ HD/
> total 0
> drwx---r-x  93 user  staff  3162 Nov 23 01:17 EyeTV Archive

**Comment by essandess** [comment]
Thanks for reporting this. I'll have my sleeves rolled up to work on issue #63 for a bit, and I suspect the fix will affect this, so please hold tight. I've gotten independent confirmation that the fixes for #62 got things working for several people. I'd suggest an uninstall/delete old .dmg's and a clean install of the latest release to confirm the issue. I also have the EyeTV archive on an external drive and eat my own dog food, so I doubt it's that.

**Comment by essandess** [comment]
@tmikkonen, would you please download v3.4 and do a round of uninstall/install/logout/login/test record and tell me if you still see this issue?

**Comment by tmikkonen** [comment]
I have good news, the issue is gone with v3.4. In the test I did the commercials were properly marked after recording stopped and also skipped when watching.
A humble bow for your great work!
