### ISSUE TITLE
Change detect_method in comskip.ini

### ISSUE THREAD

**Issue by mlcrow** [essandess/etv-comskip#66]
Per [issue #47](https://github.com/erikkaashoek/Comskip/issues/47) with erikkaashoek for Comskip, he informed me 

> There is a bug in the CC data processing that causes a crash on Mac but not on PC

Until this bug is sorted out, I suggest changing the detect_method in the provided comskip.ini to 111 from 127.

**Comment by essandess** [comment]
I've been unable to tickle this bug, and CC detection is useful to me. I'll close this issue and reopen it if I ever see it.
