### ISSUE TITLE
Cannot find Install ETVComSkip File

### ISSUE THREAD

**Issue by Wildcat1** [essandess/etv-comskip#68]
I must be missing something but I don't see an Install ETVComskip labelled script or file in this current git fork, please help.

**Comment by essandess** [comment]
https://github.com/essandess/etv-comskip/blob/master/src/scripts/Install.applescript
https://github.com/essandess/etv-comskip/releases/download/v3.5.3/ETVComskip-3.5.3-10.11.dmg
