### ISSUE TITLE
QXPScriptingAdditions Error

### ISSUE THREAD

**Issue by teknoziz** [essandess/etv-comskip#70]
Trying to run MarkCommercials manually receives this error: osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/QXPScriptingAdditions.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist. Thoughts? Using El Capitan with version 3.5.3. It does seem to complete the marking process, however.

**Comment by essandess** [comment]
Never seen that before and your versions look correct.

Options appear to be:

1. Ignore it if it's working
2. Try an earlier [release](../releases)
3. Recompile yourself on your box
4. Upgrade to latest OS
